-- ═══════════════════════════════════════════════════════════════════════
-- JARVIS Supabase Schema Setup
-- Run this script in your Supabase SQL Editor (https://supabase.com/dashboard)
-- ═══════════════════════════════════════════════════════════════════════

-- 1. Enable pgvector extension (for vector search memory)
create extension if not exists vector;

-- 2. Conversations Table
create table if not exists public.conversations (
    id text primary key,
    title text not null default 'Untitled Conversation',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    message_count integer not null default 0,
    metadata jsonb default '{}'::jsonb
);

-- 3. Messages Table
create table if not exists public.messages (
    id bigint generated by default as identity primary key,
    conversation_id text references public.conversations(id) on delete cascade,
    role text not null,
    content text not null,
    step_index integer default 0,
    timestamp timestamptz not null default now(),
    tool_calls jsonb
);

-- 4. Jarvis Memory Table (Vector Store)
create table if not exists public.jarvis_memory (
    id text primary key,
    role text not null,
    content text not null,
    embedding vector(384),
    created_at timestamptz not null default now()
);

-- 5. Indexes
create index if not exists idx_messages_conversation_id on public.messages(conversation_id);
create index if not exists idx_conversations_updated_at on public.conversations(updated_at desc);

-- 6. RPC Function for Vector Match
create or replace function match_jarvis_memory (
  query_embedding vector(384),
  match_threshold float,
  match_count int
)
returns table (
  id text,
  role text,
  content text,
  similarity float
)
language sql stable
as $$
  select
    jarvis_memory.id,
    jarvis_memory.role,
    jarvis_memory.content,
    1 - (jarvis_memory.embedding <=> query_embedding) as similarity
  from jarvis_memory
  where 1 - (jarvis_memory.embedding <=> query_embedding) > match_threshold
  order by jarvis_memory.embedding <=> query_embedding
  limit match_count;
$$;

-- 7. Enable RLS and permissive policies
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.jarvis_memory enable row level security;

drop policy if exists "Allow full access to conversations" on public.conversations;
create policy "Allow full access to conversations" on public.conversations for all using (true) with check (true);

drop policy if exists "Allow full access to messages" on public.messages;
create policy "Allow full access to messages" on public.messages for all using (true) with check (true);

drop policy if exists "Allow full access to jarvis_memory" on public.jarvis_memory;
create policy "Allow full access to jarvis_memory" on public.jarvis_memory for all using (true) with check (true);
